### PR TITLE
Use the tech-docs template as a gem

### PR DESCRIPTION
**Pull request by tijmenb**
This uses the new tech-docs gem (https://github.com/alphagov/tech-docs-gem/pull/1) to import layouts, styles and other assets.

The resulting site is exactly the same except for the `<title>` of the reference page.

Context: https://github.com/alphagov/tech-docs-template/issues/126

### CODE REVIEW

**Comment by kevindew** [comment]
"+44 −4,440" 😀 Looks great. Nice to free all those files.

I've a nasty feeling that this may not be deployable since the AWS switch so I might need to look into that. Are you planning to wait until Tech docs is out before merging?

I think we have some CSS modifications for the beta badge - do you know if they're caught?

**Comment by tijmenb** [comment]
Do you mean `.wip-banner`? That didn't seem to be used.

**Comment by kevindew** [comment]
Nah - I could see stylesheet changes from this PR: https://github.com/alphagov/govuk-content-api-docs/pull/29/files could well be that it came full circle and is now consistent with tech docs again.

**Comment by tijmenb** [comment]
I'm not sure how, but on the resulting site the beta banner is still blue. In any case, it *should* be blue so if it isn't we should fix it in the tech docs gem.

**Comment by kevindew** [comment]
Great, sounds good then. 👍

**Comment by tijmenb** [comment]
@kevindew this is now updated to use the released gem.

**Pull request merged**
